### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by HazeFlexin** [laazyboy13/linux-csgo-external#1]
What's the possibility of making a enemies only version of this and maybe adding other things to it?

**Comment by ericek111** [comment]
If you can compile the program, you must be able to change 1 line :) Otherwise get out of Linux, please.

**Comment by HazeFlexin** [comment]
No I can't, If you literally just commented to talk shit fuck off nerd.
besides that
~cry about it~

**Comment by maaatts** [comment]
On a scale of 10 to 11, how autistic are you?

**Comment by laazyboy13** [comment]
> On a scale of 10 to 11, how autistic are you?

12 actually. 

Closing this issue, I'm not fixing something this simple. Might add it in a rewrite of the cheat, but am lazy so don't expect anything.
