### ISSUE TITLE
Doesn't work...?

### ISSUE THREAD

**Issue by Superchet** [laazyboy13/linux-csgo-external#18]
I open it and it says 
GlowObject Size: 38
Found client_client.so [e5ee5000]
Glow Pointer Call Reference: 0xe645b684 | Offset: 576684
Glow function address: e6a020e0
Glow function address offset: b1d0e0
Glow Array: eb813e60

Cached 249 networked classes
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  33 (X_GrabKey)
  Serial number of failed request:  10
  Current serial number in output stream:  11

I reverted to 32bit btw

**Comment by DmitryArtyomov** [comment]
That's a problem with key binding. I just commented out the lines which were the trouble

**Comment by Superchet** [comment]
Thanks
/closed
