### ISSUE TITLE
Not locating csgo

### ISSUE THREAD

**Issue by WantedFreak** [laazyboy13/linux-csgo-external#20]
It gets stuck on Log Path
`s0beit linux hack version 1.3 
Log Path [/home/xzilla/linux-csgo-external/build/]
`
Shows noting in log, only Hack Loaded...
Im using Arch Linux and latest version of csgo

**Comment by WantedFreak** [comment]
My bad, changed `f (remote::FindProcessByName("csgo_linux", &csgo)) {` to `f (remote::FindProcessByName("csgo_linux64", &csgo)) {`
and it works now

**Comment by bryantwilliam** [comment]
Sorry to comment on a closed issue, but have you considered using the latest fork: 
https://github.com/McSwaggens/linux-csgo-external
or the new internal made by McSwaggens:
https://github.com/McSwaggens/AimTux

**Comment by WantedFreak** [comment]
Yes I did. I found the first one you linked and it works just fine :)
That second one looks interesting.. Will try AimTux on my dummy account later
