### ISSUE TITLE
What happens?

### ISSUE THREAD

**Issue by Dupiepoo** [laazyboy13/linux-csgo-external#5]
g dependencies of target csgo_external
[ 20%] Building CXX object CMakeFiles/csgo_external.dir/log.cpp.o
[ 40%] Building CXX object CMakeFiles/csgo_external.dir/remote.cpp.o
[ 60%] Building CXX object CMakeFiles/csgo_external.dir/netvar.cpp.o
[ 80%] Building CXX object CMakeFiles/csgo_external.dir/hack.cpp.o
[100%] Building CXX object CMakeFiles/csgo_external.dir/main.cpp.o
/home/victor/Hämtningar/linux-csgo-external-master/main.cpp:2:22: fatal error: X11/Xlib.h: Filen eller katalogen finns inte
 #include <X11/Xlib.h>
                      ^
compilation terminated.
make[2]: **\* [CMakeFiles/csgo_external.dir/main.cpp.o] Fel 1
make[1]: **\* [CMakeFiles/csgo_external.dir/all] Fel 2
make: **\* [all] Fel 2
victor@smaug:~/Hämtningar/linux-csgo-external-master
I'm pretty new to linux so I don't understand but i'd be more than happy if you help me :)

**Comment by kaby47** [comment]
You are missing the Xlib-dev libs. I don't know which distribution you're on, but:
_sudo apt-get install libx11-dev_
_sudo apt-get install libx11-dev:i386_
fixed it for me (Debian Jessie)

**Comment by RedNapPanda** [comment]
> Look at this PR of below, https://github.com/laazyboy13/linux-csgo-external/pull/4

That PR states this:

> Create Toggle Keybind
> 
> Synopsis
> 
> Solves #2
> (Kind of)
> No toggle for just radar.
> Press a keybind to toggle the cheat.
> Notes
> 
> Requires Xlib, # apt-get libx11-dev on Debian based systems
> Bind in this Pull Request is Ctrl+Shift+X, but this is not optimal for gameplay.
> Known Bugs
> 
> Does not work with Numlock enabled.
